import Link from "next/link";

import { AppShell } from "@/components/app-shell";
import { EmptyState, SectionCard, StatCard, StatusBadge } from "@/components/ui";
import { getProductionDemandActionMessage } from "@/lib/production-demand-action-messages";
import { getProductionDemandDeltaDetail } from "@/lib/production-demand-review-data";

import { approveProductionDemandDeltaAction, rejectProductionDemandDeltaAction } from "../../../../actions";

type PageProps = {
  params: Promise<{ reviewId: string; deltaVersionId: string }>;
  searchParams: Promise<{ demand?: string }>;
};

function label(value: string) { return value.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }

export default async function ProductionDemandDeltaPage({ params, searchParams }: PageProps) {
  const [{ reviewId, deltaVersionId }, query] = await Promise.all([params, searchParams]);
  const data = await getProductionDemandDeltaDetail(reviewId, deltaVersionId);
  const message = getProductionDemandActionMessage(query.demand);
  const delta = data.delta;

  return (
    <AppShell>
      <div className="space-y-6 px-5 py-6 md:px-8">
        <div className="flex flex-wrap items-center justify-between gap-3"><Link className="text-sm font-semibold text-emerald-700 hover:text-emerald-900" href={`/production-demand/reviews/${reviewId}`}>Back to frozen review</Link><StatusBadge tone={delta.status === "approved" ? "success" : delta.status === "stale" ? "warning" : "neutral"}>{label(delta.status)}</StatusBadge></div>
        {message ? <div className={`rounded-md border px-4 py-3 text-sm font-medium ${message.tone === "danger" ? "border-red-200 bg-red-50 text-red-800" : message.tone === "warning" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`} role="status">{message.message}</div> : null}
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-slate-500">Cumulative delta v{delta.versionNumber}</p><h2 className="mt-2 text-xl font-bold text-slate-950">Current evidence versus frozen base</h2><p className="mt-1 text-sm text-slate-600">Generated {delta.createdAt}. Pending and rejected candidates never affect effective demand.</p></div><p className="font-mono text-xs text-slate-500">{delta.comparisonFingerprint.slice(0, 16)}...</p></div></section>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard label="Source changes" value={String(delta.sourceDeltaCount)} helperText={`${delta.positiveSourceCount} positive and ${delta.negativeSourceCount} negative evidence rows.`} badge="Signed" tone="info" icon="SC" /><StatCard label="Aggregate lines" value={String(delta.aggregateLineCount)} helperText="Exact facility, date, item and UOM keys. Quantities are never combined across UOMs." badge="Exact UOM" tone="neutral" icon="AL" /><StatCard label="Effective status" value={label(delta.status)} helperText="Only the one current approved cumulative version is effective." badge="Human decision" tone={delta.status === "approved" ? "success" : "neutral"} icon="ST" /></section>
        <SectionCard title="Aggregate signed changes" description="Different facilities, dates, items and UOMs never net into one another.">
          {data.deltaLines.length === 0 ? <EmptyState title="No cumulative change" description="Current active contribution evidence matches the frozen baseline." /> : <div className="overflow-x-auto rounded-md border border-slate-200"><table className="min-w-[760px] divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th className="px-4 py-3">Production key</th><th className="px-4 py-3">Signed delta</th><th className="px-4 py-3">Positive sources</th><th className="px-4 py-3">Negative sources</th></tr></thead><tbody className="divide-y divide-slate-100 bg-white">{data.deltaLines.map((line) => <tr key={line.id}><td className="px-4 py-3"><p className="font-semibold text-slate-900">{line.internalItemName}</p><p className="mt-1 text-xs text-slate-500">{line.productionDate} / facility {line.facilityId.slice(0, 8)}</p></td><td className={`px-4 py-3 font-bold ${Number(line.signedDeltaQuantity) >= 0 ? "text-emerald-700" : "text-red-700"}`}>{Number(line.signedDeltaQuantity) > 0 ? "+" : ""}{line.signedDeltaQuantity} {line.outputUom}</td><td className="px-4 py-3 text-slate-600">{line.positiveSourceCount}</td><td className="px-4 py-3 text-slate-600">{line.negativeSourceCount}</td></tr>)}</tbody></table></div>}
        </SectionCard>
        <SectionCard title="Source-level delta evidence" description="Moved demand retains separate negative and positive rows. Immutable IDs and signed quantities are authoritative.">
          {data.deltaEvidence.length === 0 ? <EmptyState title="No source differences" description="This is a truthful zero-delta candidate." /> : <div className="space-y-3">{data.deltaEvidence.map((evidence) => <article className="grid gap-3 rounded-md border border-slate-200 p-4 md:grid-cols-5" key={evidence.id}><div className="md:col-span-2"><p className="font-semibold text-slate-900">{evidence.internalItemName}</p><p className="mt-1 font-mono text-xs text-slate-500">Order {evidence.sourceOrderId.slice(0, 8)} / line {evidence.sourceOrderLineId.slice(0, 8)}</p><p className="mt-1 text-xs text-slate-500">{evidence.productionDate} / facility {evidence.facilityId.slice(0, 8)}</p></div><div><p className="text-xs text-slate-500">Frozen</p><p className="mt-1 font-semibold">{evidence.frozenQuantity} {evidence.outputUom}</p></div><div><p className="text-xs text-slate-500">Current</p><p className="mt-1 font-semibold">{evidence.currentQuantity} {evidence.outputUom}</p></div><div><StatusBadge tone={Number(evidence.signedDeltaQuantity) > 0 ? "success" : "warning"}>{label(evidence.changeCategory)}</StatusBadge><p className="mt-2 font-bold">{Number(evidence.signedDeltaQuantity) > 0 ? "+" : ""}{evidence.signedDeltaQuantity}</p></div></article>)}</div>}
        </SectionCard>
        {data.canManage && delta.status === "pending_review" ? <SectionCard title="Delta decision" description="Approval performs a fresh comparison. A stale candidate cannot be approved, and rejection leaves the current approved version unchanged."><div className="grid gap-4 lg:grid-cols-2"><form action={approveProductionDemandDeltaAction} className="rounded-md border border-emerald-200 bg-emerald-50 p-4"><input name="review_id" type="hidden" value={reviewId} /><input name="delta_version_id" type="hidden" value={deltaVersionId} /><p className="text-sm text-emerald-900">Approve this cumulative comparison as the one current effective adjustment.</p><button className="mt-3 rounded-md bg-emerald-700 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-800" type="submit">Approve cumulative delta</button></form><form action={rejectProductionDemandDeltaAction} className="space-y-3 rounded-md border border-slate-200 p-4"><input name="review_id" type="hidden" value={reviewId} /><input name="delta_version_id" type="hidden" value={deltaVersionId} /><label className="block text-sm font-semibold text-slate-800" htmlFor="rejection_category">Rejection reason</label><select className="w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm" id="rejection_category" name="rejection_category" required><option value="">Select reason</option><option value="source_evidence_incomplete">Source evidence incomplete</option><option value="mapping_review_required">Mapping review required</option><option value="delivery_date_review_required">Delivery date review required</option><option value="production_scope_changed">Production scope changed</option><option value="quantity_requires_confirmation">Quantity requires confirmation</option><option value="duplicate_or_invalid_source">Duplicate or invalid source</option><option value="operational_decision">Operational decision</option><option value="other">Other</option></select><label className="block text-sm font-semibold text-slate-800" htmlFor="rejection_note">Safe note (optional)</label><textarea className="min-h-20 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" id="rejection_note" maxLength={500} name="rejection_note" /><button className="rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50" type="submit">Reject candidate</button></form></div></SectionCard> : null}
      </div>
    </AppShell>
  );
}
